spring.application.name=springapp
server.port=8080


# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.jsp


spring.datasource.url=jdbc:postgresql://localhost:5432/elections
spring.datasource.username=elections
spring.datasource.password=Election@123